// Code generated by ent, DO NOT EDIT.

package healthproberesults

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the healthproberesults type in the database.
	Label = "health_probe_results"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldContext holds the string denoting the context field in the database.
	FieldContext = "context"
	// EdgeHealthProbe holds the string denoting the health_probe edge name in mutations.
	EdgeHealthProbe = "health_probe"
	// Table holds the table name of the healthproberesults in the database.
	Table = "health_probe_results"
	// HealthProbeTable is the table that holds the health_probe relation/edge.
	HealthProbeTable = "health_probe_results"
	// HealthProbeInverseTable is the table name for the HealthProbe entity.
	// It exists in this package in order to avoid circular dependency with the "healthprobe" package.
	HealthProbeInverseTable = "health_probes"
	// HealthProbeColumn is the table column denoting the health_probe relation/edge.
	HealthProbeColumn = "health_probe_health_probe_results"
)

// Columns holds all SQL columns for healthproberesults fields.
var Columns = []string{
	FieldID,
	FieldResult,
	FieldContext,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "health_probe_results"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"health_probe_health_probe_results",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ResultValidator is a validator for the "result" field. It is called by the builders before save.
	ResultValidator func(int) error
)

// OrderOption defines the ordering options for the HealthProbeResults queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByResult orders the results by the result field.
func ByResult(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResult, opts...).ToFunc()
}

// ByContext orders the results by the context field.
func ByContext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContext, opts...).ToFunc()
}

// ByHealthProbeField orders the results by health_probe field.
func ByHealthProbeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHealthProbeStep(), sql.OrderByField(field, opts...))
	}
}
func newHealthProbeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HealthProbeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, HealthProbeTable, HealthProbeColumn),
	)
}
