// Code generated by ent, DO NOT EDIT.

package healthproberesults

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gitznik/wazzup/ent/predicate"
	"github.com/gitznik/wazzup/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.FieldLTE(FieldID, id))
}

// Result applies equality check predicate on the "result" field. It's identical to ResultEQ.
func Result(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldEQ(FieldResult, vc))
}

// ResultEQ applies the EQ predicate on the "result" field.
func ResultEQ(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldEQ(FieldResult, vc))
}

// ResultNEQ applies the NEQ predicate on the "result" field.
func ResultNEQ(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldNEQ(FieldResult, vc))
}

// ResultIn applies the In predicate on the "result" field.
func ResultIn(vs ...schema.CheckResult) predicate.HealthProbeResults {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.HealthProbeResults(sql.FieldIn(FieldResult, v...))
}

// ResultNotIn applies the NotIn predicate on the "result" field.
func ResultNotIn(vs ...schema.CheckResult) predicate.HealthProbeResults {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int(vs[i])
	}
	return predicate.HealthProbeResults(sql.FieldNotIn(FieldResult, v...))
}

// ResultGT applies the GT predicate on the "result" field.
func ResultGT(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldGT(FieldResult, vc))
}

// ResultGTE applies the GTE predicate on the "result" field.
func ResultGTE(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldGTE(FieldResult, vc))
}

// ResultLT applies the LT predicate on the "result" field.
func ResultLT(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldLT(FieldResult, vc))
}

// ResultLTE applies the LTE predicate on the "result" field.
func ResultLTE(v schema.CheckResult) predicate.HealthProbeResults {
	vc := int(v)
	return predicate.HealthProbeResults(sql.FieldLTE(FieldResult, vc))
}

// HasHealthProbe applies the HasEdge predicate on the "health_probe" edge.
func HasHealthProbe() predicate.HealthProbeResults {
	return predicate.HealthProbeResults(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, HealthProbeTable, HealthProbeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHealthProbeWith applies the HasEdge predicate on the "health_probe" edge with a given conditions (other predicates).
func HasHealthProbeWith(preds ...predicate.HealthProbe) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(func(s *sql.Selector) {
		step := newHealthProbeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HealthProbeResults) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HealthProbeResults) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HealthProbeResults) predicate.HealthProbeResults {
	return predicate.HealthProbeResults(sql.NotPredicates(p))
}
