// Code generated by ent, DO NOT EDIT.

package healthprobe

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the healthprobe type in the database.
	Label = "health_probe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// EdgeHealthProbeResults holds the string denoting the health_probe_results edge name in mutations.
	EdgeHealthProbeResults = "health_probe_results"
	// Table holds the table name of the healthprobe in the database.
	Table = "health_probes"
	// HealthProbeResultsTable is the table that holds the health_probe_results relation/edge.
	HealthProbeResultsTable = "health_probe_results"
	// HealthProbeResultsInverseTable is the table name for the HealthProbeResults entity.
	// It exists in this package in order to avoid circular dependency with the "healthproberesults" package.
	HealthProbeResultsInverseTable = "health_probe_results"
	// HealthProbeResultsColumn is the table column denoting the health_probe_results relation/edge.
	HealthProbeResultsColumn = "health_probe_health_probe_results"
)

// Columns holds all SQL columns for healthprobe fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
)

// OrderOption defines the ordering options for the HealthProbe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByHealthProbeResultsCount orders the results by health_probe_results count.
func ByHealthProbeResultsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newHealthProbeResultsStep(), opts...)
	}
}

// ByHealthProbeResults orders the results by health_probe_results terms.
func ByHealthProbeResults(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHealthProbeResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newHealthProbeResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HealthProbeResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, HealthProbeResultsTable, HealthProbeResultsColumn),
	)
}
