// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HealthProbesColumns holds the columns for the "health_probes" table.
	HealthProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
	}
	// HealthProbesTable holds the schema information for the "health_probes" table.
	HealthProbesTable = &schema.Table{
		Name:       "health_probes",
		Columns:    HealthProbesColumns,
		PrimaryKey: []*schema.Column{HealthProbesColumns[0]},
	}
	// HealthProbeResultsColumns holds the columns for the "health_probe_results" table.
	HealthProbeResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "result", Type: field.TypeInt},
		{Name: "health_probe_health_probe_results", Type: field.TypeInt, Nullable: true},
	}
	// HealthProbeResultsTable holds the schema information for the "health_probe_results" table.
	HealthProbeResultsTable = &schema.Table{
		Name:       "health_probe_results",
		Columns:    HealthProbeResultsColumns,
		PrimaryKey: []*schema.Column{HealthProbeResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "health_probe_results_health_probes_health_probe_results",
				Columns:    []*schema.Column{HealthProbeResultsColumns[2]},
				RefColumns: []*schema.Column{HealthProbesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// ProbesColumns holds the columns for the "probes" table.
	ProbesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// ProbesTable holds the schema information for the "probes" table.
	ProbesTable = &schema.Table{
		Name:       "probes",
		Columns:    ProbesColumns,
		PrimaryKey: []*schema.Column{ProbesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HealthProbesTable,
		HealthProbeResultsTable,
		ProbesTable,
	}
)

func init() {
	HealthProbeResultsTable.ForeignKeys[0].RefTable = HealthProbesTable
}
