// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/gitznik/wazzup/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/probe"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// HealthProbe is the client for interacting with the HealthProbe builders.
	HealthProbe *HealthProbeClient
	// HealthProbeResults is the client for interacting with the HealthProbeResults builders.
	HealthProbeResults *HealthProbeResultsClient
	// Probe is the client for interacting with the Probe builders.
	Probe *ProbeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.HealthProbe = NewHealthProbeClient(c.config)
	c.HealthProbeResults = NewHealthProbeResultsClient(c.config)
	c.Probe = NewProbeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		HealthProbe:        NewHealthProbeClient(cfg),
		HealthProbeResults: NewHealthProbeResultsClient(cfg),
		Probe:              NewProbeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		HealthProbe:        NewHealthProbeClient(cfg),
		HealthProbeResults: NewHealthProbeResultsClient(cfg),
		Probe:              NewProbeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		HealthProbe.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.HealthProbe.Use(hooks...)
	c.HealthProbeResults.Use(hooks...)
	c.Probe.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.HealthProbe.Intercept(interceptors...)
	c.HealthProbeResults.Intercept(interceptors...)
	c.Probe.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *HealthProbeMutation:
		return c.HealthProbe.mutate(ctx, m)
	case *HealthProbeResultsMutation:
		return c.HealthProbeResults.mutate(ctx, m)
	case *ProbeMutation:
		return c.Probe.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// HealthProbeClient is a client for the HealthProbe schema.
type HealthProbeClient struct {
	config
}

// NewHealthProbeClient returns a client for the HealthProbe from the given config.
func NewHealthProbeClient(c config) *HealthProbeClient {
	return &HealthProbeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `healthprobe.Hooks(f(g(h())))`.
func (c *HealthProbeClient) Use(hooks ...Hook) {
	c.hooks.HealthProbe = append(c.hooks.HealthProbe, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `healthprobe.Intercept(f(g(h())))`.
func (c *HealthProbeClient) Intercept(interceptors ...Interceptor) {
	c.inters.HealthProbe = append(c.inters.HealthProbe, interceptors...)
}

// Create returns a builder for creating a HealthProbe entity.
func (c *HealthProbeClient) Create() *HealthProbeCreate {
	mutation := newHealthProbeMutation(c.config, OpCreate)
	return &HealthProbeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HealthProbe entities.
func (c *HealthProbeClient) CreateBulk(builders ...*HealthProbeCreate) *HealthProbeCreateBulk {
	return &HealthProbeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HealthProbeClient) MapCreateBulk(slice any, setFunc func(*HealthProbeCreate, int)) *HealthProbeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HealthProbeCreateBulk{err: fmt.Errorf("calling to HealthProbeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HealthProbeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HealthProbeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HealthProbe.
func (c *HealthProbeClient) Update() *HealthProbeUpdate {
	mutation := newHealthProbeMutation(c.config, OpUpdate)
	return &HealthProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HealthProbeClient) UpdateOne(_m *HealthProbe) *HealthProbeUpdateOne {
	mutation := newHealthProbeMutation(c.config, OpUpdateOne, withHealthProbe(_m))
	return &HealthProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HealthProbeClient) UpdateOneID(id int) *HealthProbeUpdateOne {
	mutation := newHealthProbeMutation(c.config, OpUpdateOne, withHealthProbeID(id))
	return &HealthProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HealthProbe.
func (c *HealthProbeClient) Delete() *HealthProbeDelete {
	mutation := newHealthProbeMutation(c.config, OpDelete)
	return &HealthProbeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HealthProbeClient) DeleteOne(_m *HealthProbe) *HealthProbeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HealthProbeClient) DeleteOneID(id int) *HealthProbeDeleteOne {
	builder := c.Delete().Where(healthprobe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HealthProbeDeleteOne{builder}
}

// Query returns a query builder for HealthProbe.
func (c *HealthProbeClient) Query() *HealthProbeQuery {
	return &HealthProbeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHealthProbe},
		inters: c.Interceptors(),
	}
}

// Get returns a HealthProbe entity by its id.
func (c *HealthProbeClient) Get(ctx context.Context, id int) (*HealthProbe, error) {
	return c.Query().Where(healthprobe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HealthProbeClient) GetX(ctx context.Context, id int) *HealthProbe {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHealthProbeResults queries the health_probe_results edge of a HealthProbe.
func (c *HealthProbeClient) QueryHealthProbeResults(_m *HealthProbe) *HealthProbeResultsQuery {
	query := (&HealthProbeResultsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(healthprobe.Table, healthprobe.FieldID, id),
			sqlgraph.To(healthproberesults.Table, healthproberesults.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, healthprobe.HealthProbeResultsTable, healthprobe.HealthProbeResultsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HealthProbeClient) Hooks() []Hook {
	return c.hooks.HealthProbe
}

// Interceptors returns the client interceptors.
func (c *HealthProbeClient) Interceptors() []Interceptor {
	return c.inters.HealthProbe
}

func (c *HealthProbeClient) mutate(ctx context.Context, m *HealthProbeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HealthProbeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HealthProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HealthProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HealthProbeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown HealthProbe mutation op: %q", m.Op())
	}
}

// HealthProbeResultsClient is a client for the HealthProbeResults schema.
type HealthProbeResultsClient struct {
	config
}

// NewHealthProbeResultsClient returns a client for the HealthProbeResults from the given config.
func NewHealthProbeResultsClient(c config) *HealthProbeResultsClient {
	return &HealthProbeResultsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `healthproberesults.Hooks(f(g(h())))`.
func (c *HealthProbeResultsClient) Use(hooks ...Hook) {
	c.hooks.HealthProbeResults = append(c.hooks.HealthProbeResults, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `healthproberesults.Intercept(f(g(h())))`.
func (c *HealthProbeResultsClient) Intercept(interceptors ...Interceptor) {
	c.inters.HealthProbeResults = append(c.inters.HealthProbeResults, interceptors...)
}

// Create returns a builder for creating a HealthProbeResults entity.
func (c *HealthProbeResultsClient) Create() *HealthProbeResultsCreate {
	mutation := newHealthProbeResultsMutation(c.config, OpCreate)
	return &HealthProbeResultsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of HealthProbeResults entities.
func (c *HealthProbeResultsClient) CreateBulk(builders ...*HealthProbeResultsCreate) *HealthProbeResultsCreateBulk {
	return &HealthProbeResultsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *HealthProbeResultsClient) MapCreateBulk(slice any, setFunc func(*HealthProbeResultsCreate, int)) *HealthProbeResultsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &HealthProbeResultsCreateBulk{err: fmt.Errorf("calling to HealthProbeResultsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*HealthProbeResultsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &HealthProbeResultsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for HealthProbeResults.
func (c *HealthProbeResultsClient) Update() *HealthProbeResultsUpdate {
	mutation := newHealthProbeResultsMutation(c.config, OpUpdate)
	return &HealthProbeResultsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HealthProbeResultsClient) UpdateOne(_m *HealthProbeResults) *HealthProbeResultsUpdateOne {
	mutation := newHealthProbeResultsMutation(c.config, OpUpdateOne, withHealthProbeResults(_m))
	return &HealthProbeResultsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HealthProbeResultsClient) UpdateOneID(id int) *HealthProbeResultsUpdateOne {
	mutation := newHealthProbeResultsMutation(c.config, OpUpdateOne, withHealthProbeResultsID(id))
	return &HealthProbeResultsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for HealthProbeResults.
func (c *HealthProbeResultsClient) Delete() *HealthProbeResultsDelete {
	mutation := newHealthProbeResultsMutation(c.config, OpDelete)
	return &HealthProbeResultsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HealthProbeResultsClient) DeleteOne(_m *HealthProbeResults) *HealthProbeResultsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *HealthProbeResultsClient) DeleteOneID(id int) *HealthProbeResultsDeleteOne {
	builder := c.Delete().Where(healthproberesults.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HealthProbeResultsDeleteOne{builder}
}

// Query returns a query builder for HealthProbeResults.
func (c *HealthProbeResultsClient) Query() *HealthProbeResultsQuery {
	return &HealthProbeResultsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeHealthProbeResults},
		inters: c.Interceptors(),
	}
}

// Get returns a HealthProbeResults entity by its id.
func (c *HealthProbeResultsClient) Get(ctx context.Context, id int) (*HealthProbeResults, error) {
	return c.Query().Where(healthproberesults.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HealthProbeResultsClient) GetX(ctx context.Context, id int) *HealthProbeResults {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryHealthProbe queries the health_probe edge of a HealthProbeResults.
func (c *HealthProbeResultsClient) QueryHealthProbe(_m *HealthProbeResults) *HealthProbeQuery {
	query := (&HealthProbeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(healthproberesults.Table, healthproberesults.FieldID, id),
			sqlgraph.To(healthprobe.Table, healthprobe.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, healthproberesults.HealthProbeTable, healthproberesults.HealthProbeColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *HealthProbeResultsClient) Hooks() []Hook {
	return c.hooks.HealthProbeResults
}

// Interceptors returns the client interceptors.
func (c *HealthProbeResultsClient) Interceptors() []Interceptor {
	return c.inters.HealthProbeResults
}

func (c *HealthProbeResultsClient) mutate(ctx context.Context, m *HealthProbeResultsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&HealthProbeResultsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&HealthProbeResultsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&HealthProbeResultsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&HealthProbeResultsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown HealthProbeResults mutation op: %q", m.Op())
	}
}

// ProbeClient is a client for the Probe schema.
type ProbeClient struct {
	config
}

// NewProbeClient returns a client for the Probe from the given config.
func NewProbeClient(c config) *ProbeClient {
	return &ProbeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `probe.Hooks(f(g(h())))`.
func (c *ProbeClient) Use(hooks ...Hook) {
	c.hooks.Probe = append(c.hooks.Probe, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `probe.Intercept(f(g(h())))`.
func (c *ProbeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Probe = append(c.inters.Probe, interceptors...)
}

// Create returns a builder for creating a Probe entity.
func (c *ProbeClient) Create() *ProbeCreate {
	mutation := newProbeMutation(c.config, OpCreate)
	return &ProbeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Probe entities.
func (c *ProbeClient) CreateBulk(builders ...*ProbeCreate) *ProbeCreateBulk {
	return &ProbeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ProbeClient) MapCreateBulk(slice any, setFunc func(*ProbeCreate, int)) *ProbeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ProbeCreateBulk{err: fmt.Errorf("calling to ProbeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ProbeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ProbeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Probe.
func (c *ProbeClient) Update() *ProbeUpdate {
	mutation := newProbeMutation(c.config, OpUpdate)
	return &ProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ProbeClient) UpdateOne(_m *Probe) *ProbeUpdateOne {
	mutation := newProbeMutation(c.config, OpUpdateOne, withProbe(_m))
	return &ProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ProbeClient) UpdateOneID(id int) *ProbeUpdateOne {
	mutation := newProbeMutation(c.config, OpUpdateOne, withProbeID(id))
	return &ProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Probe.
func (c *ProbeClient) Delete() *ProbeDelete {
	mutation := newProbeMutation(c.config, OpDelete)
	return &ProbeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ProbeClient) DeleteOne(_m *Probe) *ProbeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ProbeClient) DeleteOneID(id int) *ProbeDeleteOne {
	builder := c.Delete().Where(probe.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ProbeDeleteOne{builder}
}

// Query returns a query builder for Probe.
func (c *ProbeClient) Query() *ProbeQuery {
	return &ProbeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeProbe},
		inters: c.Interceptors(),
	}
}

// Get returns a Probe entity by its id.
func (c *ProbeClient) Get(ctx context.Context, id int) (*Probe, error) {
	return c.Query().Where(probe.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ProbeClient) GetX(ctx context.Context, id int) *Probe {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ProbeClient) Hooks() []Hook {
	return c.hooks.Probe
}

// Interceptors returns the client interceptors.
func (c *ProbeClient) Interceptors() []Interceptor {
	return c.inters.Probe
}

func (c *ProbeClient) mutate(ctx context.Context, m *ProbeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ProbeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ProbeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ProbeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ProbeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Probe mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		HealthProbe, HealthProbeResults, Probe []ent.Hook
	}
	inters struct {
		HealthProbe, HealthProbeResults, Probe []ent.Interceptor
	}
)
