// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/schema"
)

// HealthProbeResults is the model entity for the HealthProbeResults schema.
type HealthProbeResults struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Result holds the value of the "result" field.
	Result schema.CheckResult `json:"result,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HealthProbeResultsQuery when eager-loading is set.
	Edges                             HealthProbeResultsEdges `json:"edges"`
	health_probe_health_probe_results *int
	selectValues                      sql.SelectValues
}

// HealthProbeResultsEdges holds the relations/edges for other nodes in the graph.
type HealthProbeResultsEdges struct {
	// HealthProbe holds the value of the health_probe edge.
	HealthProbe *HealthProbe `json:"health_probe,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HealthProbeOrErr returns the HealthProbe value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HealthProbeResultsEdges) HealthProbeOrErr() (*HealthProbe, error) {
	if e.HealthProbe != nil {
		return e.HealthProbe, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: healthprobe.Label}
	}
	return nil, &NotLoadedError{edge: "health_probe"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HealthProbeResults) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case healthproberesults.FieldID, healthproberesults.FieldResult:
			values[i] = new(sql.NullInt64)
		case healthproberesults.ForeignKeys[0]: // health_probe_health_probe_results
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HealthProbeResults fields.
func (_m *HealthProbeResults) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case healthproberesults.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case healthproberesults.FieldResult:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = schema.CheckResult(value.Int64)
			}
		case healthproberesults.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field health_probe_health_probe_results", value)
			} else if value.Valid {
				_m.health_probe_health_probe_results = new(int)
				*_m.health_probe_health_probe_results = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HealthProbeResults.
// This includes values selected through modifiers, order, etc.
func (_m *HealthProbeResults) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHealthProbe queries the "health_probe" edge of the HealthProbeResults entity.
func (_m *HealthProbeResults) QueryHealthProbe() *HealthProbeQuery {
	return NewHealthProbeResultsClient(_m.config).QueryHealthProbe(_m)
}

// Update returns a builder for updating this HealthProbeResults.
// Note that you need to call HealthProbeResults.Unwrap() before calling this method if this HealthProbeResults
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HealthProbeResults) Update() *HealthProbeResultsUpdateOne {
	return NewHealthProbeResultsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HealthProbeResults entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HealthProbeResults) Unwrap() *HealthProbeResults {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HealthProbeResults is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HealthProbeResults) String() string {
	var builder strings.Builder
	builder.WriteString("HealthProbeResults(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteByte(')')
	return builder.String()
}

// HealthProbeResultsSlice is a parsable slice of HealthProbeResults.
type HealthProbeResultsSlice []*HealthProbeResults
