// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
)

// HealthProbeCreate is the builder for creating a HealthProbe entity.
type HealthProbeCreate struct {
	config
	mutation *HealthProbeMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *HealthProbeCreate) SetName(v string) *HealthProbeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *HealthProbeCreate) SetURL(v string) *HealthProbeCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (_c *HealthProbeCreate) SetDeactivatedAt(v time.Time) *HealthProbeCreate {
	_c.mutation.SetDeactivatedAt(v)
	return _c
}

// SetNillableDeactivatedAt sets the "deactivated_at" field if the given value is not nil.
func (_c *HealthProbeCreate) SetNillableDeactivatedAt(v *time.Time) *HealthProbeCreate {
	if v != nil {
		_c.SetDeactivatedAt(*v)
	}
	return _c
}

// AddHealthProbeResultIDs adds the "health_probe_results" edge to the HealthProbeResults entity by IDs.
func (_c *HealthProbeCreate) AddHealthProbeResultIDs(ids ...int) *HealthProbeCreate {
	_c.mutation.AddHealthProbeResultIDs(ids...)
	return _c
}

// AddHealthProbeResults adds the "health_probe_results" edges to the HealthProbeResults entity.
func (_c *HealthProbeCreate) AddHealthProbeResults(v ...*HealthProbeResults) *HealthProbeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddHealthProbeResultIDs(ids...)
}

// Mutation returns the HealthProbeMutation object of the builder.
func (_c *HealthProbeCreate) Mutation() *HealthProbeMutation {
	return _c.mutation
}

// Save creates the HealthProbe in the database.
func (_c *HealthProbeCreate) Save(ctx context.Context) (*HealthProbe, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *HealthProbeCreate) SaveX(ctx context.Context) *HealthProbe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthProbeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthProbeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *HealthProbeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "HealthProbe.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "HealthProbe.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := healthprobe.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "HealthProbe.url": %w`, err)}
		}
	}
	return nil
}

func (_c *HealthProbeCreate) sqlSave(ctx context.Context) (*HealthProbe, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *HealthProbeCreate) createSpec() (*HealthProbe, *sqlgraph.CreateSpec) {
	var (
		_node = &HealthProbe{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(healthprobe.Table, sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(healthprobe.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(healthprobe.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.DeactivatedAt(); ok {
		_spec.SetField(healthprobe.FieldDeactivatedAt, field.TypeTime, value)
		_node.DeactivatedAt = value
	}
	if nodes := _c.mutation.HealthProbeResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// HealthProbeCreateBulk is the builder for creating many HealthProbe entities in bulk.
type HealthProbeCreateBulk struct {
	config
	err      error
	builders []*HealthProbeCreate
}

// Save creates the HealthProbe entities in the database.
func (_c *HealthProbeCreateBulk) Save(ctx context.Context) ([]*HealthProbe, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*HealthProbe, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HealthProbeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *HealthProbeCreateBulk) SaveX(ctx context.Context) []*HealthProbe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *HealthProbeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *HealthProbeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
