// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/predicate"
	"github.com/gitznik/wazzup/ent/schema"
)

// HealthProbeResultsUpdate is the builder for updating HealthProbeResults entities.
type HealthProbeResultsUpdate struct {
	config
	hooks    []Hook
	mutation *HealthProbeResultsMutation
}

// Where appends a list predicates to the HealthProbeResultsUpdate builder.
func (_u *HealthProbeResultsUpdate) Where(ps ...predicate.HealthProbeResults) *HealthProbeResultsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetResult sets the "result" field.
func (_u *HealthProbeResultsUpdate) SetResult(v schema.CheckResult) *HealthProbeResultsUpdate {
	_u.mutation.ResetResult()
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *HealthProbeResultsUpdate) SetNillableResult(v *schema.CheckResult) *HealthProbeResultsUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// AddResult adds value to the "result" field.
func (_u *HealthProbeResultsUpdate) AddResult(v schema.CheckResult) *HealthProbeResultsUpdate {
	_u.mutation.AddResult(v)
	return _u
}

// SetContext sets the "context" field.
func (_u *HealthProbeResultsUpdate) SetContext(v string) *HealthProbeResultsUpdate {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *HealthProbeResultsUpdate) SetNillableContext(v *string) *HealthProbeResultsUpdate {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *HealthProbeResultsUpdate) ClearContext() *HealthProbeResultsUpdate {
	_u.mutation.ClearContext()
	return _u
}

// SetHealthProbeID sets the "health_probe" edge to the HealthProbe entity by ID.
func (_u *HealthProbeResultsUpdate) SetHealthProbeID(id int) *HealthProbeResultsUpdate {
	_u.mutation.SetHealthProbeID(id)
	return _u
}

// SetNillableHealthProbeID sets the "health_probe" edge to the HealthProbe entity by ID if the given value is not nil.
func (_u *HealthProbeResultsUpdate) SetNillableHealthProbeID(id *int) *HealthProbeResultsUpdate {
	if id != nil {
		_u = _u.SetHealthProbeID(*id)
	}
	return _u
}

// SetHealthProbe sets the "health_probe" edge to the HealthProbe entity.
func (_u *HealthProbeResultsUpdate) SetHealthProbe(v *HealthProbe) *HealthProbeResultsUpdate {
	return _u.SetHealthProbeID(v.ID)
}

// Mutation returns the HealthProbeResultsMutation object of the builder.
func (_u *HealthProbeResultsUpdate) Mutation() *HealthProbeResultsMutation {
	return _u.mutation
}

// ClearHealthProbe clears the "health_probe" edge to the HealthProbe entity.
func (_u *HealthProbeResultsUpdate) ClearHealthProbe() *HealthProbeResultsUpdate {
	_u.mutation.ClearHealthProbe()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HealthProbeResultsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthProbeResultsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HealthProbeResultsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthProbeResultsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthProbeResultsUpdate) check() error {
	if v, ok := _u.mutation.Result(); ok {
		if err := healthproberesults.ResultValidator(int(v)); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "HealthProbeResults.result": %w`, err)}
		}
	}
	return nil
}

func (_u *HealthProbeResultsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthproberesults.Table, healthproberesults.Columns, sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(healthproberesults.FieldResult, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResult(); ok {
		_spec.AddField(healthproberesults.FieldResult, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(healthproberesults.FieldContext, field.TypeString, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(healthproberesults.FieldContext, field.TypeString)
	}
	if _u.mutation.HealthProbeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthproberesults.HealthProbeTable,
			Columns: []string{healthproberesults.HealthProbeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HealthProbeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthproberesults.HealthProbeTable,
			Columns: []string{healthproberesults.HealthProbeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthproberesults.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HealthProbeResultsUpdateOne is the builder for updating a single HealthProbeResults entity.
type HealthProbeResultsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HealthProbeResultsMutation
}

// SetResult sets the "result" field.
func (_u *HealthProbeResultsUpdateOne) SetResult(v schema.CheckResult) *HealthProbeResultsUpdateOne {
	_u.mutation.ResetResult()
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *HealthProbeResultsUpdateOne) SetNillableResult(v *schema.CheckResult) *HealthProbeResultsUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// AddResult adds value to the "result" field.
func (_u *HealthProbeResultsUpdateOne) AddResult(v schema.CheckResult) *HealthProbeResultsUpdateOne {
	_u.mutation.AddResult(v)
	return _u
}

// SetContext sets the "context" field.
func (_u *HealthProbeResultsUpdateOne) SetContext(v string) *HealthProbeResultsUpdateOne {
	_u.mutation.SetContext(v)
	return _u
}

// SetNillableContext sets the "context" field if the given value is not nil.
func (_u *HealthProbeResultsUpdateOne) SetNillableContext(v *string) *HealthProbeResultsUpdateOne {
	if v != nil {
		_u.SetContext(*v)
	}
	return _u
}

// ClearContext clears the value of the "context" field.
func (_u *HealthProbeResultsUpdateOne) ClearContext() *HealthProbeResultsUpdateOne {
	_u.mutation.ClearContext()
	return _u
}

// SetHealthProbeID sets the "health_probe" edge to the HealthProbe entity by ID.
func (_u *HealthProbeResultsUpdateOne) SetHealthProbeID(id int) *HealthProbeResultsUpdateOne {
	_u.mutation.SetHealthProbeID(id)
	return _u
}

// SetNillableHealthProbeID sets the "health_probe" edge to the HealthProbe entity by ID if the given value is not nil.
func (_u *HealthProbeResultsUpdateOne) SetNillableHealthProbeID(id *int) *HealthProbeResultsUpdateOne {
	if id != nil {
		_u = _u.SetHealthProbeID(*id)
	}
	return _u
}

// SetHealthProbe sets the "health_probe" edge to the HealthProbe entity.
func (_u *HealthProbeResultsUpdateOne) SetHealthProbe(v *HealthProbe) *HealthProbeResultsUpdateOne {
	return _u.SetHealthProbeID(v.ID)
}

// Mutation returns the HealthProbeResultsMutation object of the builder.
func (_u *HealthProbeResultsUpdateOne) Mutation() *HealthProbeResultsMutation {
	return _u.mutation
}

// ClearHealthProbe clears the "health_probe" edge to the HealthProbe entity.
func (_u *HealthProbeResultsUpdateOne) ClearHealthProbe() *HealthProbeResultsUpdateOne {
	_u.mutation.ClearHealthProbe()
	return _u
}

// Where appends a list predicates to the HealthProbeResultsUpdate builder.
func (_u *HealthProbeResultsUpdateOne) Where(ps ...predicate.HealthProbeResults) *HealthProbeResultsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HealthProbeResultsUpdateOne) Select(field string, fields ...string) *HealthProbeResultsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HealthProbeResults entity.
func (_u *HealthProbeResultsUpdateOne) Save(ctx context.Context) (*HealthProbeResults, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthProbeResultsUpdateOne) SaveX(ctx context.Context) *HealthProbeResults {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HealthProbeResultsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthProbeResultsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthProbeResultsUpdateOne) check() error {
	if v, ok := _u.mutation.Result(); ok {
		if err := healthproberesults.ResultValidator(int(v)); err != nil {
			return &ValidationError{Name: "result", err: fmt.Errorf(`ent: validator failed for field "HealthProbeResults.result": %w`, err)}
		}
	}
	return nil
}

func (_u *HealthProbeResultsUpdateOne) sqlSave(ctx context.Context) (_node *HealthProbeResults, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthproberesults.Table, healthproberesults.Columns, sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HealthProbeResults.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, healthproberesults.FieldID)
		for _, f := range fields {
			if !healthproberesults.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != healthproberesults.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(healthproberesults.FieldResult, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResult(); ok {
		_spec.AddField(healthproberesults.FieldResult, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Context(); ok {
		_spec.SetField(healthproberesults.FieldContext, field.TypeString, value)
	}
	if _u.mutation.ContextCleared() {
		_spec.ClearField(healthproberesults.FieldContext, field.TypeString)
	}
	if _u.mutation.HealthProbeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthproberesults.HealthProbeTable,
			Columns: []string{healthproberesults.HealthProbeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HealthProbeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthproberesults.HealthProbeTable,
			Columns: []string{healthproberesults.HealthProbeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HealthProbeResults{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthproberesults.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
