// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitznik/wazzup/ent/healthprobe"
)

// HealthProbe is the model entity for the HealthProbe schema.
type HealthProbe struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// DeactivatedAt holds the value of the "deactivated_at" field.
	DeactivatedAt time.Time `json:"deactivated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HealthProbeQuery when eager-loading is set.
	Edges        HealthProbeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HealthProbeEdges holds the relations/edges for other nodes in the graph.
type HealthProbeEdges struct {
	// HealthProbeResults holds the value of the health_probe_results edge.
	HealthProbeResults []*HealthProbeResults `json:"health_probe_results,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// HealthProbeResultsOrErr returns the HealthProbeResults value or an error if the edge
// was not loaded in eager-loading.
func (e HealthProbeEdges) HealthProbeResultsOrErr() ([]*HealthProbeResults, error) {
	if e.loadedTypes[0] {
		return e.HealthProbeResults, nil
	}
	return nil, &NotLoadedError{edge: "health_probe_results"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HealthProbe) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case healthprobe.FieldID:
			values[i] = new(sql.NullInt64)
		case healthprobe.FieldName, healthprobe.FieldURL:
			values[i] = new(sql.NullString)
		case healthprobe.FieldDeactivatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HealthProbe fields.
func (_m *HealthProbe) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case healthprobe.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case healthprobe.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case healthprobe.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case healthprobe.FieldDeactivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deactivated_at", values[i])
			} else if value.Valid {
				_m.DeactivatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HealthProbe.
// This includes values selected through modifiers, order, etc.
func (_m *HealthProbe) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryHealthProbeResults queries the "health_probe_results" edge of the HealthProbe entity.
func (_m *HealthProbe) QueryHealthProbeResults() *HealthProbeResultsQuery {
	return NewHealthProbeClient(_m.config).QueryHealthProbeResults(_m)
}

// Update returns a builder for updating this HealthProbe.
// Note that you need to call HealthProbe.Unwrap() before calling this method if this HealthProbe
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HealthProbe) Update() *HealthProbeUpdateOne {
	return NewHealthProbeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HealthProbe entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HealthProbe) Unwrap() *HealthProbe {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HealthProbe is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HealthProbe) String() string {
	var builder strings.Builder
	builder.WriteString("HealthProbe(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("deactivated_at=")
	builder.WriteString(_m.DeactivatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// HealthProbes is a parsable slice of HealthProbe.
type HealthProbes []*HealthProbe
