// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/predicate"
)

// HealthProbeUpdate is the builder for updating HealthProbe entities.
type HealthProbeUpdate struct {
	config
	hooks    []Hook
	mutation *HealthProbeMutation
}

// Where appends a list predicates to the HealthProbeUpdate builder.
func (_u *HealthProbeUpdate) Where(ps ...predicate.HealthProbe) *HealthProbeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *HealthProbeUpdate) SetName(v string) *HealthProbeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HealthProbeUpdate) SetNillableName(v *string) *HealthProbeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HealthProbeUpdate) SetURL(v string) *HealthProbeUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HealthProbeUpdate) SetNillableURL(v *string) *HealthProbeUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// AddHealthProbeResultIDs adds the "health_probe_results" edge to the HealthProbeResults entity by IDs.
func (_u *HealthProbeUpdate) AddHealthProbeResultIDs(ids ...int) *HealthProbeUpdate {
	_u.mutation.AddHealthProbeResultIDs(ids...)
	return _u
}

// AddHealthProbeResults adds the "health_probe_results" edges to the HealthProbeResults entity.
func (_u *HealthProbeUpdate) AddHealthProbeResults(v ...*HealthProbeResults) *HealthProbeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHealthProbeResultIDs(ids...)
}

// Mutation returns the HealthProbeMutation object of the builder.
func (_u *HealthProbeUpdate) Mutation() *HealthProbeMutation {
	return _u.mutation
}

// ClearHealthProbeResults clears all "health_probe_results" edges to the HealthProbeResults entity.
func (_u *HealthProbeUpdate) ClearHealthProbeResults() *HealthProbeUpdate {
	_u.mutation.ClearHealthProbeResults()
	return _u
}

// RemoveHealthProbeResultIDs removes the "health_probe_results" edge to HealthProbeResults entities by IDs.
func (_u *HealthProbeUpdate) RemoveHealthProbeResultIDs(ids ...int) *HealthProbeUpdate {
	_u.mutation.RemoveHealthProbeResultIDs(ids...)
	return _u
}

// RemoveHealthProbeResults removes "health_probe_results" edges to HealthProbeResults entities.
func (_u *HealthProbeUpdate) RemoveHealthProbeResults(v ...*HealthProbeResults) *HealthProbeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHealthProbeResultIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HealthProbeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthProbeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HealthProbeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthProbeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthProbeUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := healthprobe.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "HealthProbe.url": %w`, err)}
		}
	}
	return nil
}

func (_u *HealthProbeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthprobe.Table, healthprobe.Columns, sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(healthprobe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(healthprobe.FieldURL, field.TypeString, value)
	}
	if _u.mutation.HealthProbeResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHealthProbeResultsIDs(); len(nodes) > 0 && !_u.mutation.HealthProbeResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HealthProbeResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthprobe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HealthProbeUpdateOne is the builder for updating a single HealthProbe entity.
type HealthProbeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HealthProbeMutation
}

// SetName sets the "name" field.
func (_u *HealthProbeUpdateOne) SetName(v string) *HealthProbeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HealthProbeUpdateOne) SetNillableName(v *string) *HealthProbeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HealthProbeUpdateOne) SetURL(v string) *HealthProbeUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HealthProbeUpdateOne) SetNillableURL(v *string) *HealthProbeUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// AddHealthProbeResultIDs adds the "health_probe_results" edge to the HealthProbeResults entity by IDs.
func (_u *HealthProbeUpdateOne) AddHealthProbeResultIDs(ids ...int) *HealthProbeUpdateOne {
	_u.mutation.AddHealthProbeResultIDs(ids...)
	return _u
}

// AddHealthProbeResults adds the "health_probe_results" edges to the HealthProbeResults entity.
func (_u *HealthProbeUpdateOne) AddHealthProbeResults(v ...*HealthProbeResults) *HealthProbeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHealthProbeResultIDs(ids...)
}

// Mutation returns the HealthProbeMutation object of the builder.
func (_u *HealthProbeUpdateOne) Mutation() *HealthProbeMutation {
	return _u.mutation
}

// ClearHealthProbeResults clears all "health_probe_results" edges to the HealthProbeResults entity.
func (_u *HealthProbeUpdateOne) ClearHealthProbeResults() *HealthProbeUpdateOne {
	_u.mutation.ClearHealthProbeResults()
	return _u
}

// RemoveHealthProbeResultIDs removes the "health_probe_results" edge to HealthProbeResults entities by IDs.
func (_u *HealthProbeUpdateOne) RemoveHealthProbeResultIDs(ids ...int) *HealthProbeUpdateOne {
	_u.mutation.RemoveHealthProbeResultIDs(ids...)
	return _u
}

// RemoveHealthProbeResults removes "health_probe_results" edges to HealthProbeResults entities.
func (_u *HealthProbeUpdateOne) RemoveHealthProbeResults(v ...*HealthProbeResults) *HealthProbeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHealthProbeResultIDs(ids...)
}

// Where appends a list predicates to the HealthProbeUpdate builder.
func (_u *HealthProbeUpdateOne) Where(ps ...predicate.HealthProbe) *HealthProbeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HealthProbeUpdateOne) Select(field string, fields ...string) *HealthProbeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HealthProbe entity.
func (_u *HealthProbeUpdateOne) Save(ctx context.Context) (*HealthProbe, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HealthProbeUpdateOne) SaveX(ctx context.Context) *HealthProbe {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HealthProbeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HealthProbeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HealthProbeUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := healthprobe.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "HealthProbe.url": %w`, err)}
		}
	}
	return nil
}

func (_u *HealthProbeUpdateOne) sqlSave(ctx context.Context) (_node *HealthProbe, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthprobe.Table, healthprobe.Columns, sqlgraph.NewFieldSpec(healthprobe.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HealthProbe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, healthprobe.FieldID)
		for _, f := range fields {
			if !healthprobe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != healthprobe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(healthprobe.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(healthprobe.FieldURL, field.TypeString, value)
	}
	if _u.mutation.HealthProbeResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHealthProbeResultsIDs(); len(nodes) > 0 && !_u.mutation.HealthProbeResultsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HealthProbeResultsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   healthprobe.HealthProbeResultsTable,
			Columns: []string{healthprobe.HealthProbeResultsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(healthproberesults.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HealthProbe{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthprobe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
