// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/predicate"
	"github.com/gitznik/wazzup/ent/probe"
	"github.com/gitznik/wazzup/ent/schema"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHealthProbe        = "HealthProbe"
	TypeHealthProbeResults = "HealthProbeResults"
	TypeProbe              = "Probe"
)

// HealthProbeMutation represents an operation that mutates the HealthProbe nodes in the graph.
type HealthProbeMutation struct {
	config
	op                          Op
	typ                         string
	id                          *int
	name                        *string
	url                         *string
	deactivated_at              *time.Time
	clearedFields               map[string]struct{}
	health_probe_results        map[int]struct{}
	removedhealth_probe_results map[int]struct{}
	clearedhealth_probe_results bool
	done                        bool
	oldValue                    func(context.Context) (*HealthProbe, error)
	predicates                  []predicate.HealthProbe
}

var _ ent.Mutation = (*HealthProbeMutation)(nil)

// healthprobeOption allows management of the mutation configuration using functional options.
type healthprobeOption func(*HealthProbeMutation)

// newHealthProbeMutation creates new mutation for the HealthProbe entity.
func newHealthProbeMutation(c config, op Op, opts ...healthprobeOption) *HealthProbeMutation {
	m := &HealthProbeMutation{
		config:        c,
		op:            op,
		typ:           TypeHealthProbe,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHealthProbeID sets the ID field of the mutation.
func withHealthProbeID(id int) healthprobeOption {
	return func(m *HealthProbeMutation) {
		var (
			err   error
			once  sync.Once
			value *HealthProbe
		)
		m.oldValue = func(ctx context.Context) (*HealthProbe, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().HealthProbe.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHealthProbe sets the old HealthProbe of the mutation.
func withHealthProbe(node *HealthProbe) healthprobeOption {
	return func(m *HealthProbeMutation) {
		m.oldValue = func(context.Context) (*HealthProbe, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HealthProbeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HealthProbeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HealthProbeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HealthProbeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().HealthProbe.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *HealthProbeMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *HealthProbeMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the HealthProbe entity.
// If the HealthProbe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HealthProbeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *HealthProbeMutation) ResetName() {
	m.name = nil
}

// SetURL sets the "url" field.
func (m *HealthProbeMutation) SetURL(s string) {
	m.url = &s
}

// URL returns the value of the "url" field in the mutation.
func (m *HealthProbeMutation) URL() (r string, exists bool) {
	v := m.url
	if v == nil {
		return
	}
	return *v, true
}

// OldURL returns the old "url" field's value of the HealthProbe entity.
// If the HealthProbe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HealthProbeMutation) OldURL(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldURL is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldURL requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldURL: %w", err)
	}
	return oldValue.URL, nil
}

// ResetURL resets all changes to the "url" field.
func (m *HealthProbeMutation) ResetURL() {
	m.url = nil
}

// SetDeactivatedAt sets the "deactivated_at" field.
func (m *HealthProbeMutation) SetDeactivatedAt(t time.Time) {
	m.deactivated_at = &t
}

// DeactivatedAt returns the value of the "deactivated_at" field in the mutation.
func (m *HealthProbeMutation) DeactivatedAt() (r time.Time, exists bool) {
	v := m.deactivated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeactivatedAt returns the old "deactivated_at" field's value of the HealthProbe entity.
// If the HealthProbe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HealthProbeMutation) OldDeactivatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeactivatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeactivatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeactivatedAt: %w", err)
	}
	return oldValue.DeactivatedAt, nil
}

// ClearDeactivatedAt clears the value of the "deactivated_at" field.
func (m *HealthProbeMutation) ClearDeactivatedAt() {
	m.deactivated_at = nil
	m.clearedFields[healthprobe.FieldDeactivatedAt] = struct{}{}
}

// DeactivatedAtCleared returns if the "deactivated_at" field was cleared in this mutation.
func (m *HealthProbeMutation) DeactivatedAtCleared() bool {
	_, ok := m.clearedFields[healthprobe.FieldDeactivatedAt]
	return ok
}

// ResetDeactivatedAt resets all changes to the "deactivated_at" field.
func (m *HealthProbeMutation) ResetDeactivatedAt() {
	m.deactivated_at = nil
	delete(m.clearedFields, healthprobe.FieldDeactivatedAt)
}

// AddHealthProbeResultIDs adds the "health_probe_results" edge to the HealthProbeResults entity by ids.
func (m *HealthProbeMutation) AddHealthProbeResultIDs(ids ...int) {
	if m.health_probe_results == nil {
		m.health_probe_results = make(map[int]struct{})
	}
	for i := range ids {
		m.health_probe_results[ids[i]] = struct{}{}
	}
}

// ClearHealthProbeResults clears the "health_probe_results" edge to the HealthProbeResults entity.
func (m *HealthProbeMutation) ClearHealthProbeResults() {
	m.clearedhealth_probe_results = true
}

// HealthProbeResultsCleared reports if the "health_probe_results" edge to the HealthProbeResults entity was cleared.
func (m *HealthProbeMutation) HealthProbeResultsCleared() bool {
	return m.clearedhealth_probe_results
}

// RemoveHealthProbeResultIDs removes the "health_probe_results" edge to the HealthProbeResults entity by IDs.
func (m *HealthProbeMutation) RemoveHealthProbeResultIDs(ids ...int) {
	if m.removedhealth_probe_results == nil {
		m.removedhealth_probe_results = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.health_probe_results, ids[i])
		m.removedhealth_probe_results[ids[i]] = struct{}{}
	}
}

// RemovedHealthProbeResults returns the removed IDs of the "health_probe_results" edge to the HealthProbeResults entity.
func (m *HealthProbeMutation) RemovedHealthProbeResultsIDs() (ids []int) {
	for id := range m.removedhealth_probe_results {
		ids = append(ids, id)
	}
	return
}

// HealthProbeResultsIDs returns the "health_probe_results" edge IDs in the mutation.
func (m *HealthProbeMutation) HealthProbeResultsIDs() (ids []int) {
	for id := range m.health_probe_results {
		ids = append(ids, id)
	}
	return
}

// ResetHealthProbeResults resets all changes to the "health_probe_results" edge.
func (m *HealthProbeMutation) ResetHealthProbeResults() {
	m.health_probe_results = nil
	m.clearedhealth_probe_results = false
	m.removedhealth_probe_results = nil
}

// Where appends a list predicates to the HealthProbeMutation builder.
func (m *HealthProbeMutation) Where(ps ...predicate.HealthProbe) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HealthProbeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HealthProbeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.HealthProbe, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HealthProbeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HealthProbeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (HealthProbe).
func (m *HealthProbeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HealthProbeMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, healthprobe.FieldName)
	}
	if m.url != nil {
		fields = append(fields, healthprobe.FieldURL)
	}
	if m.deactivated_at != nil {
		fields = append(fields, healthprobe.FieldDeactivatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HealthProbeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case healthprobe.FieldName:
		return m.Name()
	case healthprobe.FieldURL:
		return m.URL()
	case healthprobe.FieldDeactivatedAt:
		return m.DeactivatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HealthProbeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case healthprobe.FieldName:
		return m.OldName(ctx)
	case healthprobe.FieldURL:
		return m.OldURL(ctx)
	case healthprobe.FieldDeactivatedAt:
		return m.OldDeactivatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown HealthProbe field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HealthProbeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case healthprobe.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case healthprobe.FieldURL:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetURL(v)
		return nil
	case healthprobe.FieldDeactivatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeactivatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown HealthProbe field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HealthProbeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HealthProbeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HealthProbeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown HealthProbe numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HealthProbeMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(healthprobe.FieldDeactivatedAt) {
		fields = append(fields, healthprobe.FieldDeactivatedAt)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HealthProbeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HealthProbeMutation) ClearField(name string) error {
	switch name {
	case healthprobe.FieldDeactivatedAt:
		m.ClearDeactivatedAt()
		return nil
	}
	return fmt.Errorf("unknown HealthProbe nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HealthProbeMutation) ResetField(name string) error {
	switch name {
	case healthprobe.FieldName:
		m.ResetName()
		return nil
	case healthprobe.FieldURL:
		m.ResetURL()
		return nil
	case healthprobe.FieldDeactivatedAt:
		m.ResetDeactivatedAt()
		return nil
	}
	return fmt.Errorf("unknown HealthProbe field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HealthProbeMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.health_probe_results != nil {
		edges = append(edges, healthprobe.EdgeHealthProbeResults)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HealthProbeMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case healthprobe.EdgeHealthProbeResults:
		ids := make([]ent.Value, 0, len(m.health_probe_results))
		for id := range m.health_probe_results {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HealthProbeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedhealth_probe_results != nil {
		edges = append(edges, healthprobe.EdgeHealthProbeResults)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HealthProbeMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case healthprobe.EdgeHealthProbeResults:
		ids := make([]ent.Value, 0, len(m.removedhealth_probe_results))
		for id := range m.removedhealth_probe_results {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HealthProbeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedhealth_probe_results {
		edges = append(edges, healthprobe.EdgeHealthProbeResults)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HealthProbeMutation) EdgeCleared(name string) bool {
	switch name {
	case healthprobe.EdgeHealthProbeResults:
		return m.clearedhealth_probe_results
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HealthProbeMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown HealthProbe unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HealthProbeMutation) ResetEdge(name string) error {
	switch name {
	case healthprobe.EdgeHealthProbeResults:
		m.ResetHealthProbeResults()
		return nil
	}
	return fmt.Errorf("unknown HealthProbe edge %s", name)
}

// HealthProbeResultsMutation represents an operation that mutates the HealthProbeResults nodes in the graph.
type HealthProbeResultsMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	result              *schema.CheckResult
	addresult           *schema.CheckResult
	context             *string
	clearedFields       map[string]struct{}
	health_probe        *int
	clearedhealth_probe bool
	done                bool
	oldValue            func(context.Context) (*HealthProbeResults, error)
	predicates          []predicate.HealthProbeResults
}

var _ ent.Mutation = (*HealthProbeResultsMutation)(nil)

// healthproberesultsOption allows management of the mutation configuration using functional options.
type healthproberesultsOption func(*HealthProbeResultsMutation)

// newHealthProbeResultsMutation creates new mutation for the HealthProbeResults entity.
func newHealthProbeResultsMutation(c config, op Op, opts ...healthproberesultsOption) *HealthProbeResultsMutation {
	m := &HealthProbeResultsMutation{
		config:        c,
		op:            op,
		typ:           TypeHealthProbeResults,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHealthProbeResultsID sets the ID field of the mutation.
func withHealthProbeResultsID(id int) healthproberesultsOption {
	return func(m *HealthProbeResultsMutation) {
		var (
			err   error
			once  sync.Once
			value *HealthProbeResults
		)
		m.oldValue = func(ctx context.Context) (*HealthProbeResults, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().HealthProbeResults.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHealthProbeResults sets the old HealthProbeResults of the mutation.
func withHealthProbeResults(node *HealthProbeResults) healthproberesultsOption {
	return func(m *HealthProbeResultsMutation) {
		m.oldValue = func(context.Context) (*HealthProbeResults, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HealthProbeResultsMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HealthProbeResultsMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HealthProbeResultsMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HealthProbeResultsMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().HealthProbeResults.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetResult sets the "result" field.
func (m *HealthProbeResultsMutation) SetResult(sr schema.CheckResult) {
	m.result = &sr
	m.addresult = nil
}

// Result returns the value of the "result" field in the mutation.
func (m *HealthProbeResultsMutation) Result() (r schema.CheckResult, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the HealthProbeResults entity.
// If the HealthProbeResults object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HealthProbeResultsMutation) OldResult(ctx context.Context) (v schema.CheckResult, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// AddResult adds sr to the "result" field.
func (m *HealthProbeResultsMutation) AddResult(sr schema.CheckResult) {
	if m.addresult != nil {
		*m.addresult += sr
	} else {
		m.addresult = &sr
	}
}

// AddedResult returns the value that was added to the "result" field in this mutation.
func (m *HealthProbeResultsMutation) AddedResult() (r schema.CheckResult, exists bool) {
	v := m.addresult
	if v == nil {
		return
	}
	return *v, true
}

// ResetResult resets all changes to the "result" field.
func (m *HealthProbeResultsMutation) ResetResult() {
	m.result = nil
	m.addresult = nil
}

// SetContext sets the "context" field.
func (m *HealthProbeResultsMutation) SetContext(s string) {
	m.context = &s
}

// Context returns the value of the "context" field in the mutation.
func (m *HealthProbeResultsMutation) Context() (r string, exists bool) {
	v := m.context
	if v == nil {
		return
	}
	return *v, true
}

// OldContext returns the old "context" field's value of the HealthProbeResults entity.
// If the HealthProbeResults object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HealthProbeResultsMutation) OldContext(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldContext is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldContext requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldContext: %w", err)
	}
	return oldValue.Context, nil
}

// ClearContext clears the value of the "context" field.
func (m *HealthProbeResultsMutation) ClearContext() {
	m.context = nil
	m.clearedFields[healthproberesults.FieldContext] = struct{}{}
}

// ContextCleared returns if the "context" field was cleared in this mutation.
func (m *HealthProbeResultsMutation) ContextCleared() bool {
	_, ok := m.clearedFields[healthproberesults.FieldContext]
	return ok
}

// ResetContext resets all changes to the "context" field.
func (m *HealthProbeResultsMutation) ResetContext() {
	m.context = nil
	delete(m.clearedFields, healthproberesults.FieldContext)
}

// SetHealthProbeID sets the "health_probe" edge to the HealthProbe entity by id.
func (m *HealthProbeResultsMutation) SetHealthProbeID(id int) {
	m.health_probe = &id
}

// ClearHealthProbe clears the "health_probe" edge to the HealthProbe entity.
func (m *HealthProbeResultsMutation) ClearHealthProbe() {
	m.clearedhealth_probe = true
}

// HealthProbeCleared reports if the "health_probe" edge to the HealthProbe entity was cleared.
func (m *HealthProbeResultsMutation) HealthProbeCleared() bool {
	return m.clearedhealth_probe
}

// HealthProbeID returns the "health_probe" edge ID in the mutation.
func (m *HealthProbeResultsMutation) HealthProbeID() (id int, exists bool) {
	if m.health_probe != nil {
		return *m.health_probe, true
	}
	return
}

// HealthProbeIDs returns the "health_probe" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// HealthProbeID instead. It exists only for internal usage by the builders.
func (m *HealthProbeResultsMutation) HealthProbeIDs() (ids []int) {
	if id := m.health_probe; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetHealthProbe resets all changes to the "health_probe" edge.
func (m *HealthProbeResultsMutation) ResetHealthProbe() {
	m.health_probe = nil
	m.clearedhealth_probe = false
}

// Where appends a list predicates to the HealthProbeResultsMutation builder.
func (m *HealthProbeResultsMutation) Where(ps ...predicate.HealthProbeResults) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HealthProbeResultsMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HealthProbeResultsMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.HealthProbeResults, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HealthProbeResultsMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HealthProbeResultsMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (HealthProbeResults).
func (m *HealthProbeResultsMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HealthProbeResultsMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.result != nil {
		fields = append(fields, healthproberesults.FieldResult)
	}
	if m.context != nil {
		fields = append(fields, healthproberesults.FieldContext)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HealthProbeResultsMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case healthproberesults.FieldResult:
		return m.Result()
	case healthproberesults.FieldContext:
		return m.Context()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HealthProbeResultsMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case healthproberesults.FieldResult:
		return m.OldResult(ctx)
	case healthproberesults.FieldContext:
		return m.OldContext(ctx)
	}
	return nil, fmt.Errorf("unknown HealthProbeResults field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HealthProbeResultsMutation) SetField(name string, value ent.Value) error {
	switch name {
	case healthproberesults.FieldResult:
		v, ok := value.(schema.CheckResult)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case healthproberesults.FieldContext:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetContext(v)
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HealthProbeResultsMutation) AddedFields() []string {
	var fields []string
	if m.addresult != nil {
		fields = append(fields, healthproberesults.FieldResult)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HealthProbeResultsMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case healthproberesults.FieldResult:
		return m.AddedResult()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HealthProbeResultsMutation) AddField(name string, value ent.Value) error {
	switch name {
	case healthproberesults.FieldResult:
		v, ok := value.(schema.CheckResult)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddResult(v)
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HealthProbeResultsMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(healthproberesults.FieldContext) {
		fields = append(fields, healthproberesults.FieldContext)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HealthProbeResultsMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HealthProbeResultsMutation) ClearField(name string) error {
	switch name {
	case healthproberesults.FieldContext:
		m.ClearContext()
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HealthProbeResultsMutation) ResetField(name string) error {
	switch name {
	case healthproberesults.FieldResult:
		m.ResetResult()
		return nil
	case healthproberesults.FieldContext:
		m.ResetContext()
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HealthProbeResultsMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.health_probe != nil {
		edges = append(edges, healthproberesults.EdgeHealthProbe)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HealthProbeResultsMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case healthproberesults.EdgeHealthProbe:
		if id := m.health_probe; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HealthProbeResultsMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HealthProbeResultsMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HealthProbeResultsMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedhealth_probe {
		edges = append(edges, healthproberesults.EdgeHealthProbe)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HealthProbeResultsMutation) EdgeCleared(name string) bool {
	switch name {
	case healthproberesults.EdgeHealthProbe:
		return m.clearedhealth_probe
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HealthProbeResultsMutation) ClearEdge(name string) error {
	switch name {
	case healthproberesults.EdgeHealthProbe:
		m.ClearHealthProbe()
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HealthProbeResultsMutation) ResetEdge(name string) error {
	switch name {
	case healthproberesults.EdgeHealthProbe:
		m.ResetHealthProbe()
		return nil
	}
	return fmt.Errorf("unknown HealthProbeResults edge %s", name)
}

// ProbeMutation represents an operation that mutates the Probe nodes in the graph.
type ProbeMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Probe, error)
	predicates    []predicate.Probe
}

var _ ent.Mutation = (*ProbeMutation)(nil)

// probeOption allows management of the mutation configuration using functional options.
type probeOption func(*ProbeMutation)

// newProbeMutation creates new mutation for the Probe entity.
func newProbeMutation(c config, op Op, opts ...probeOption) *ProbeMutation {
	m := &ProbeMutation{
		config:        c,
		op:            op,
		typ:           TypeProbe,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withProbeID sets the ID field of the mutation.
func withProbeID(id int) probeOption {
	return func(m *ProbeMutation) {
		var (
			err   error
			once  sync.Once
			value *Probe
		)
		m.oldValue = func(ctx context.Context) (*Probe, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Probe.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withProbe sets the old Probe of the mutation.
func withProbe(node *Probe) probeOption {
	return func(m *ProbeMutation) {
		m.oldValue = func(context.Context) (*Probe, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ProbeMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ProbeMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ProbeMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ProbeMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Probe.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *ProbeMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ProbeMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Probe entity.
// If the Probe object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ProbeMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ProbeMutation) ResetName() {
	m.name = nil
}

// Where appends a list predicates to the ProbeMutation builder.
func (m *ProbeMutation) Where(ps ...predicate.Probe) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ProbeMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ProbeMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Probe, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ProbeMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ProbeMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Probe).
func (m *ProbeMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ProbeMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, probe.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ProbeMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case probe.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ProbeMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case probe.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown Probe field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProbeMutation) SetField(name string, value ent.Value) error {
	switch name {
	case probe.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown Probe field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ProbeMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ProbeMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ProbeMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Probe numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ProbeMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ProbeMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ProbeMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Probe nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ProbeMutation) ResetField(name string) error {
	switch name {
	case probe.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown Probe field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ProbeMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ProbeMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ProbeMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ProbeMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ProbeMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ProbeMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ProbeMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Probe unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ProbeMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Probe edge %s", name)
}
