// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/gitznik/wazzup/ent/healthprobe"
	"github.com/gitznik/wazzup/ent/healthproberesults"
	"github.com/gitznik/wazzup/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	healthprobeFields := schema.HealthProbe{}.Fields()
	_ = healthprobeFields
	// healthprobeDescURL is the schema descriptor for url field.
	healthprobeDescURL := healthprobeFields[1].Descriptor()
	// healthprobe.URLValidator is a validator for the "url" field. It is called by the builders before save.
	healthprobe.URLValidator = healthprobeDescURL.Validators[0].(func(string) error)
	healthproberesultsFields := schema.HealthProbeResults{}.Fields()
	_ = healthproberesultsFields
	// healthproberesultsDescResult is the schema descriptor for result field.
	healthproberesultsDescResult := healthproberesultsFields[0].Descriptor()
	// healthproberesults.ResultValidator is a validator for the "result" field. It is called by the builders before save.
	healthproberesults.ResultValidator = healthproberesultsDescResult.Validators[0].(func(int) error)
}
