// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// HealthProbe is the predicate function for healthprobe builders.
type HealthProbe func(*sql.Selector)

// HealthProbeResults is the predicate function for healthproberesults builders.
type HealthProbeResults func(*sql.Selector)

// Probe is the predicate function for probe builders.
type Probe func(*sql.Selector)
